name = "backend"
compatibility_date = "2023-12-01"



[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiM2IwNjkzNTgtYTcxMy00MTcwLTg2NTItNWZjZjA5M2U0MjBhIiwidGVuYW50X2lkIjoiMWM3YzMyN2I1MmM2ZGRmZDUyNDQ5MTY0Yjg5MjFmZGM2NzhjNGM0N2RiMWQ3ZTEwMThiMWExZmM4NmI1MjU0OCIsImludGVybmFsX3NlY3JldCI6IjMxN2E2ZjM0LTVhMjktNDQ1Zi1hNzE3LTM3OTI3ZTg2MzM3MCJ9.Rp81p8kwtLvl2f-AsZJ7EaxwWAZp6rL9fhhRZ3JYk-U"
JWT_SECRET = "MYJWTTOKEN"

